server:
  port: 8090

spring:
  application:
    name: "loan"
  profiles:
    active: "prod"
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:bank_db
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071"
  rabbitmq:
    host: "localhost"
    port: 5672
    stream:
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"