build:
  version: "3.0"

card:
  message: "Welcome to the Card Service"
  contactDetails:
    name: "Hoàng Tấn Phú Quốc - phuquocchamp"
    email: "hoangtanphuquoc@gmail.com"
  onCallSupport:
    - (+84) 123 456 789
    - (+84) 123 456 669